#+OPTIONS: toc:nil
#+begin_export markdown
---
title: "My Love for Cars"
date: 2025-12-04
description: "I explain what I truly feel when I drive a car"
---
#+end_export
# date: YYYY-MM-DD

#+TOC: headlines 2

* Introduction


* Torque vs Power
These are the two figures you see when you look at the specifications of an
engine. To truly understand what they mean, imagine a wrench you're using to
turn a bolt. The speed and agility of your hands don't matter when you've got to
get a tight bolt to turn. For this you need to be able to exert a lot of force
on the wrench to twist it. This is the *torque*. Now once you have the wrench
spinning, you don't need to put in a lot of force to keep it moving.

Things are tricker to understand when we talk about the speed at which you turn
the wrench. Your hands need to be quick and agile to be able to turn it faster.
You definitely need some twisting force applied, but the speed at which the
wrench actually turns depends on how *quickly* you can deliver that force. I'll
try not to get too mathematical but power is \(\frac{\text{work}}{\text{time}}
\), and this is roughly \( \frac{\text{force} \times \text{output}}{\text{time}} \).
For a given twisting force applied, if you get more \(
\frac{\text{output}}{\text{time}} \) done, you have more *power*.

