#+OPTIONS: toc:nil
#+begin_export markdown
---
title: "My Love for Cars"
date: 2025-12-04
description: "I explain what I truly feel when I drive a car"
---
#+end_export
# date: YYYY-MM-DD

#+TOC: headlines 2

* Introduction
I've gone from driving shopping trolleys as a kid, to driving poorly maintained
Tata Sumos. Some might say I've gone pro at the same thing 😂. These two events
are about 15 years apart, although I still find driving shopping trolleys fun.


* Growing Up
An anecdote of mine which I heard from my parents, starts off with my dad's
friends pointing at a car. "That is a car", said those friends to a 4 year old
Praanesh. Seemingly, the 4 year old Praanesh corrected them by saying it's a BMW
😂. As a child, I was aware of all major car brands, and I would tell by their
sound if they run on Diesel or Petrol. Nothing to write home about, but
definitely puts me on the list of people aware of cars.

* Figured out Everything
By the age of about 12, I understood how most things in a car work. For example:
- basic principles behind the working of an engine
- how a transmission system enables a fixed range of rpm to work with different
  speeds of your wheels
- what a clutch does in a transmission system
- the primary types of rims
- how to operate the stalks on the steering rack

When I travel in a car, I'd keenly observe everything the driver does. Even as a
passenger, I'd mentally drive 



* Diesel vs Petrol


** Torque vs Power
These are the two figures you see when you look at the specifications of an
engine. To truly understand what they mean, imagine a wrench you're using to
turn a bolt. The speed and agility of your hands don't matter when you've got to
get a tight bolt to turn. For this you need to be able to exert a lot of force
on the wrench to twist it. This is the *torque*. Now once you have the wrench
spinning, you don't need to put in a lot of force to keep it moving.

Things are tricker to understand when we talk about the speed at which you turn
the wrench. Your hands need to be quick and agile to be able to turn it faster.
You definitely need some twisting force applied, but the speed at which the
wrench actually turns depends on how *quickly* you can deliver that force. I'll
try not to get too mathematical but power is \(\frac{\text{work}}{\text{time}}
\). And if you recollect the basics of physics, \(work = force \times displacement\)
and $displacement$ signifies some form of output given by the force. In our
case, it's rotations of the wrench. The more rotations per minute you can make,
the more work you perform, and hence the more power you create.

** Why Diesel?
The weight of a car is hauled by an internal combustion engine, which can either
use diesel or petrol as a fuel. In a diesel engine, first the air is compressed
(so the pressure and temperature is higher). Now, the fuel is injected and it
burns because of the high temperature and pressure of air. Air is compressed way
more in case of a diesel engine when compared to a petrol engine, and this
creates a lot of force (hence higher torque output). But the effect is a heavier
construction which is best at pulling, not sprinting.

My Maruti Suzuki Ritz (ZDI, 2014) is powered by the ever-reliable Fiat 1.3 MJD,
which produced 74 hp at 4000 rpm, and 190 N.m of torque at 2000 rpm. The peak
torque output results in a rather dramatic pull. You can feel the entire front
end lift up, and feel yourself being pushed in your seat, as you leave everyone
else on the road in dust. Even the sound of the engine pumps your blood faster.
At 2000 rpm, all the sound of the diesel clatter fades away, and makes way for a
roar from the engine accompanied by the sound of air gushing by.

This experience is typical in almost any turbocharged diesel engine, so don't
worry about finding a Ritz to try this out 😂.

** What about Petrol?
In a petrol engine, both the fuel and air are mixed, and then compressed
together. Petrol is easier to ignite than diesel, but this compressed air is
still not enough. You need an external spark (provided by a spark plug) to help.


