#+OPTIONS: toc:nil
#+begin_export markdown
---
title: "Walk, Talk and Type"
date: 2026-04-13
description: "The foundation that helps me in doing what I love doing"
---
#+end_export
# date: YYYY-MM-DD

#+TOC: headlines 2

* Second-Nature: The idea I'm tryna sell
When you gain a lot of experience in driving a car, moving the vehicle starts
becoming second-nature to you. I don't mean your hands and legs moving on their
own or just magically turning into wires which connect the car and your brain.
You can still turn the wheel however you like. You can choose to floor the
accelerator, or you can choose to have smooth acceleration/retardation.

The car becomes second-nature to you when you find yourself doing very trivial,
routine actions effortlessly. Say you're shifting from 2nd gear to 3rd gear,
exactly after 1.5K rpm, and smoothly releasing the clutch like you've been doing
for years. Perfecting this exact sequence of oddly specific steps is when you
say moving the car is second-nature to you.

