#+OPTIONS: toc:nil
#+begin_export markdown
---
title: "Walk, Talk and Type"
date: 2026-04-13
description: "The foundation that helps me in doing what I love doing"
---
#+end_export
# date: YYYY-MM-DD

#+TOC: headlines 2

* The idea I'm tryna sell
When you gain a lot of experience in driving a car, moving the vehicle starts
becoming second-nature to you. Sure, it's not like your hands and legs start
moving on their own. You can still turn the wheel however you like. You can
choose to floor the accelerator, or you can choose to have smooth
acceleration/retardation.

The car becomes second-nature to you when you find yourself doing very trivial,
routine actions effortlessly. It could be shifting from 2nd gear to 3rd gear,
exactly after 1.7K rpm, and smoothly releasing the clutch like you've been doing
for years. It's when you do this exact sequence of oddly specific steps again
and again, and not your hands and legs just magically turning into this wires
which connect your brain and the car.


